import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  htmap: [{type: 'autogenerated', dirName: 'htmap'}],
  formapi: [{type: 'autogenerated', dirName: 'form-api'}],
  customies: [{type: 'autogenerated', dirName: 'customies'}],
};

export default sidebars;