import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  htmap: [
    {
      type: 'category',
      label: 'Creating Plugins',
      items: [
        {
          type: 'autogenerated',
          dirName: 'htmap', 
        },
      ],
    },
  ],
  formapi: [
    {
      type: 'category',
      label: 'FormAPI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'form-api', 
        },
      ],
    },
  ],
  customise: [
    {
      type: 'category',
      label: 'Customise',
      items: [
        {
          type: 'autogenerated',
          dirName: 'customise', 
        },
      ],
    },
  ],
};

export default sidebars;