local_backend: true

backend:
  name: github
  branch: main 
  repo: Amblydia/Pocketmine-School
  open_authoring: true

# These lines should *not* be indented
media_folder: "static/img/*" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., yyyy-MM-dd-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'docs'
    label: 'HTMAP'
    folder: docs/htmap
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number } 
      - { name: body, label: Body, widget: markdown }


# collections:
# - name: blog
#   label: "blog"
#   folder: blog
#   identifier_field: title
#   extension: md
#   widget: "list"
#   create: true
#   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#   fields:
#     - { name: title, label: Title, widget: string }
#     - { name: body, label: Body, widget: markdown }
#     - { name: slug, label: Slug, widget: string }
#     - label: "Tags"
#       name: "tags"
#       widget: "list"
#     - label: "Authors"
#       name: "authors" 
#       widget: "list"
#       fields:
#         - { name: name, label: Name, widget: string }
#         - { name: title, label: Title, widget: string } 
#         - { name: url, label: URL, widget: string } 
#         - { name: imageUrl, label: ImageURL, widget: string } 

# - name: htmap
#   label: "How To Make A Plugin"
#   folder: "docs/htmap"
#   create: true
#   sortable_fields: ['sidebar_position']
#   fields:
#     - { name: title, label: Title, widget: string }
#     - { name: body, label: Body, widget: markdown }
#     - { name: slug, label: Slug, widget: string }
#     - { name: sidebar_label, label: Sidebar Label, widget: string }
#     - { name: sidebar_position, label: Sidebar Position, widget: number } 

# - name: form-api
#   label: "How To Use FormAPI"
#   folder: "docs/form-api"
#   create: true
#   sortable_fields: ['sidebar_position']
#   fields:
#     - { name: title, label: Title, widget: string }
#     - { name: body, label: Body, widget: markdown }
#     - { name: slug, label: Slug, widget: string }
#     - { name: sidebar_label, label: Sidebar Label, widget: string }
#     - { name: sidebar_position, label: Sidebar Position, widget: number } 

# - name: customies
#   label: "How To Use Customies"
#   folder: "docs/customies"
#   create: true
#   sortable_fields: ['sidebar_position']
#   fields:
#     - { name: title, label: Title, widget: string }
#     - { name: body, label: Body, widget: markdown }
#     - { name: slug, label: Slug, widget: string }
#     - { name: sidebar_label, label: Sidebar Label, widget: string }
#     - { name: sidebar_position, label: Sidebar Position, widget: number }

# - name: camera-system
#   label: "Camera System The basics"
#   folder: "docs/camera-system"
#   create: true
#   sortable_fields: ['sidebar_position']
#   fields:
#     - { name: title, label: Title, widget: string }
#     - { name: body, label: Body, widget: markdown }
#     - { name: slug, label: Slug, widget: string }
#     - { name: sidebar_label, label: Sidebar Label, widget: string }
#     - { name: sidebar_position, label: Sidebar Position, widget: number }  