local_backend: true

backend:
  name: github
  branch: main 
  repo: Amblydia/Pocketmine-School
  open_authoring: true

media_folder: "static/img/" 
public_folder: "/img/" 
publish_mode: editorial_workflow

collections:
  - name: 'blog' 
    label: 'Blog' 
    folder: 'blog'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' 
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - label: 'Authors' 
        name: 'authors'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - { label: 'Image', name: 'image_url', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'select', multiple: true, options: ['update', 'release'] }
      - { label: 'Image', name: 'image', widget: 'image'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'htmap'
    label: 'HTMAP'
    folder: 'docs/htmap'
    create: true
    summary: '{{sidebar_position}} - {{title}}'
    sortable_fields:
      fields: ['sidebar_position']
      default:
        field: sidebar_position
        direction: Ascending
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number, value_type: 'int', min: 1 } 
      - { name: body, label: Body, widget: markdown }

  - name: 'form-api'
    label: 'FormAPI'
    folder: 'docs/form-api'
    create: true
    summary: '{{sidebar_position}} - {{title}}'
    sortable_fields:
      fields: ['sidebar_position']
      default:
        field: sidebar_position
        direction: Ascending
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number, value_type: 'int', min: 1 } 
      - { name: body, label: Body, widget: markdown }

  - name: 'customies'
    label: 'Customies'
    folder: 'docs/customies'
    create: true
    summary: '{{sidebar_position}} - {{title}}'
    sortable_fields:
      fields: ['sidebar_position']
      default:
        field: sidebar_position
        direction: Ascending
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number, value_type: 'int', min: 1 } 
      - { name: body, label: Body, widget: markdown }

  - name: 'camera-system'
    label: 'Camera System'
    folder: 'docs/camera-system'
    create: true
    summary: '{{sidebar_position}} - {{title}}'
    sortable_fields:
      fields: ['sidebar_position']
      default:
        field: sidebar_position
        direction: Ascending
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number, value_type: 'int', min: 1 } 
      - { name: body, label: Body, widget: markdown }

  - name: 'pharynx'
    label: 'Pharynx'
    folder: 'docs/pharynx'
    create: true
    summary: '{{sidebar_position}} - {{title}}'
    sortable_fields:
      fields: ['sidebar_position']
      default:
        field: sidebar_position
        direction: Ascending
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number, value_type: 'int', min: 1 } 
      - { name: body, label: Body, widget: markdown }